### ISSUE TITLE
Seems working but not casting

### ISSUE THREAD

**Issue by Ninitage** [Rafostar/gnome-shell-extension-cast-to-tv#94] opened 2019-11-05 21:19 UTC
Hello, first, thank you, you made a great job here, however I'm experiencing a problem, I've installed it and try to cast to my chromecast connected to the same local network than my laptop.
It used to work once, but not anymore, I don't know what's wrong, I've installed it through gnome shell extensions site, freedesktop is installed by flatpak, I've installed node modules as well, restart the shell.
It's recognizing the device in the prefs panel but when I want to cast nothing happens, no videos even with transcoding options, no music, no picture... I've already checked my firewall rules, everything seems fine.
When I look gnome-shell logs through journalctl or .xsession-errors even lg console, I can't see any error occured...
Just something like freedesktop hostname got a undefined label when a cast to tv window is displayed (prefs panel, file to select to cast) but it doesn't seems to be an error and it doesn't seem to prevent the window displaying.
I'm pretty sure this trouble doesn't come from the chromecast device because it works like a charm with my android phone...
I'm running ubuntu 18.04-3 LTS, Gnome 3.28, all apt packages, flatpak packages and npm seems up to date.
Could you give me a hand on this or would you have any suggestions where I could have look to find what's wrong please?
If you need further information, just let me know.

**Comment by Rafostar** [comment] 2019-11-06 07:58
Hi, first make sure you have receiver type in extension prefs correctly set to Chromecast. If it wasn't try casting again.

Otherwise lets take a look at what happens during file cast. Turn off this extension node service without disabling whole extension (from Gnome top bar menu). TV indicator icon should disappear from top bar. Then do the following:
```
cd ~/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts
DEBUG=bridge,chromecast* node server
```

After running, extension menu and indicator should reappear.
Try reproducing your problem and send me output. Stop the terminal process with Ctrl+c buttons.

**Comment by Ninitage** [comment] 2019-11-07 03:31
Hi, thanks a lot to have replied, Chromecast was correctly set in the prefs panel, it was still not working.
When I tried to turn off cast media in the gnome top bar menu, TV indicator wouldn't disappear...
Even, I gave it a try with the way that you explained me to debug it.
Here it start to stream properly like it would have to do. I don't know what did the trick, but now after stop the cast and Ctrl+c the command, it still works really well. Thank you very much by the way I feel and I apologize for wasted your time.

**Comment by Rafostar** [comment] 2019-11-07 07:45
@Ninitage 
This extension uses a separate background node service to stream media. This service is responsible for turning on/off indicator on top bar on start/exit. In your case it looks like something **killed** the node process. This resulted in turn off button not working (process wont gracefully exit since there is no process as it was killed earlier).

It is possible that some other app/process killed it (e.g. running `killall gjs` or `killall node` from terminal) or it might be a bug in the code. Background processes are started when you re-login into the desktop or reboot. So that might be your temporary solution if it happens again. If you can narrow down when it happens let me know so I can fix it.

**Comment by Ninitage** [comment] 2019-11-11 22:59
Many thanks for your help, following multiples reboot or switch off, it still working really well, but for sure if it happens once again I will try to send you an output.

**Comment by Rafostar** [comment] 2020-01-08 19:50
I created issue templates with debugging steps described here in case somebody else encounters similar issue. Therefore closing.

**Closed by Rafostar** 2020-01-08 19:50 UTC
