### ISSUE TITLE
Cant lauch in extensions 

### ISSUE THREAD

**Issue by chav3sko** [Rafostar/gnome-shell-extension-cast-to-tv#151] opened 2022-01-23 21:33 UTC
Hey im total noob ... using pop os 

this shows in gnome extesions 

The settings of extension cast-to-tv@rafostar.github.com had an error:
```
Error: Requiring Vte, version none: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
```

Stack trace:
```
@/home/linux/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/prefs.js:4:54
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Rafostar** [comment] 2022-01-23 21:38
Duplicate of #140

**Closed as completed by Rafostar** 2022-01-23 21:38 UTC

**Comment by chav3sko** [comment] 2022-01-23 21:40
Hi so there is no way to make it work rn ?

**Comment by Rafostar** [comment] 2022-01-23 21:47
> Hi so there is no way to make it work rn ?

Right now, no. GNOME is slowly porting its ecosystem to GTK4, once all we need is already on it, we can then port too.

**Comment by chav3sko** [comment] 2022-01-23 21:56
Alright thanks I was out of my mind trying to find solition for 4 hours
.... Hope they will do it asap

**Comment by chav3sko** [comment] 2022-01-23 21:56
Also thanks for reply have a nice day
