### ISSUE TITLE
Broken by ubuntu 21.10 upgrade

### ISSUE THREAD

**Issue by wvdberg** [Rafostar/gnome-shell-extension-cast-to-tv#148] opened 2021-11-26 08:38 UTC
Hi,

I upgraded ubuntu in-place from the previous 21.x version, this awesome extension stopped working. I can only assume it's the gnome version that also got bumped and is causing this.

Re-installing after setting `gsettings set org.gnome.shell disable-extension-version-validation true` gave an error during install. (No details displayed without digging).

I can dig further, if my system is in any way interesting.

Much thanks
W

**Comment by Rafostar** [comment] 2021-11-26 08:42
We do not support GNOME 40+ yet. Not all dependencies that this project uses were ported to GTK4 that recent gnome shell requires.

**Comment by Rafostar** [comment] 2021-11-26 08:42
Duplicate of #140

**Closed as completed** 2021-11-26 08:43 UTC

**Comment by wvdberg** [comment] 2021-11-26 08:45
Wow, thank you and sorry for the noise. Didn't think to look under closed issues.
Edit - no i was just an idiot sorry

**Comment by wvdberg** [comment] 2021-11-26 08:45
@Rafostar :pray:

**Comment by Rafostar** [comment] 2021-11-26 08:52
@wvdberg 

Its hard when GNOME devs suddenly do "please use GTK4 now" without waiting for all libs (that are part of GNOME ecosystem) to port to GTK4 first. I would rather not want to lose present functionalities.

Also porting this extension basically requires rewriting this whole thing almost from scratch. I will see what I can do, but I cannot promise any ETA.
