### ISSUE TITLE
GTK4

### ISSUE THREAD

**Issue by cloudsun9** [Rafostar/gnome-shell-extension-cast-to-tv#152] opened 2022-02-18 08:59 UTC
Ubuntu 21.10 Wayland

Error: Requiring Vte, version none: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded

Stack trace:
  @/home/david/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/prefs.js:4:54
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by Rafostar** [comment] 2022-02-18 22:25
Duplicate of #140

**Closed as completed by Rafostar** 2022-02-18 22:25 UTC
