### ISSUE TITLE
[Feature request] Casting desktop

### ISSUE THREAD

**Issue by uocxp** [Rafostar/gnome-shell-extension-cast-to-tv#5] opened 2019-01-10 15:34 UTC
is it possible to cast my desktop to chromecast ? If not is this feature planned ?

**Comment by Rafostar** [comment] 2019-01-10 15:57
Casting desktop is in Chrome browser (unfortunately without sound).
I made this extension as an easy way to cast files. Although casting desktop through included tools is possible, we would have to convert it to video and stream it as such. I once experimented with ffmpeg function x11grab to stream desktop, but due to converting and chromecast forced buffering the delay was too high.

**Comment by thermatk** [comment] 2019-01-12 09:19
delay is not a problem, if sound corresponds to video
it would be a cool option, just as you said with ffmpeg capturing screen from x11 and audio from pulse

**Comment by corebots** [comment] 2019-02-08 19:12
I second this request. casting the desktop with video in sync with sound is something would be really really great! Thanks for this extension btw.

**Comment by Drakulix** [comment] 2019-03-26 10:20
What should be used to implement this feature is the xdg-desktop-portal. More specifically the ScreenCast protocol: https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.impl.portal.ScreenCast

Gnome has an experimental implementation, that also works on wayland (which is not the case for x11grap) and should become stable in the near future.

While portals were specifically designed for flatpak apps, they can be used by "normal" programs and doing so is encouraged for protocols like ScreenCast.

**Comment by Rafostar** [comment] 2019-03-26 16:55
This is nice and all, but the biggest problem here is that Chromecast is too simple device to implement something like that. The only thing that official google API supports are videos, music and pictures. Finito.

I agree with you that something like this should be professionally used when designing your own sender and receiver apps. But here I have to work with the only thing that google device supports i.e. mp4 files :disappointed:

**Comment by thermatk** [comment] 2019-05-18 08:22
@Rafostar how about cvlc?
The Raspberry Pi community uses something like that 
```
cvlc screen:// :screen-fps=25 :screen-caching=100 --sout '#transcode{vcodec=MJPG,vb=0,width=1022,height=575,acodec=none}:http{mux=ogg,dst=:8080/}'
```
I guess one can just as well use H264 for video and catch the sound properly, and then it's there for anyone with VLC :+1:

**Comment by Rafostar** [comment] 2019-05-18 14:14
@thermatk Nice find. Can you try it on Wayland?
Distros started switching away from X11 (e.g. Fedora), so I would like to have this working on Wayland too.

**Comment by thermatk** [comment] 2019-05-18 22:15
I guess for wayland to work one needs vlc-git, as of now it just doesn't

Additional info for the command above, so at least it's complete under X11: 

1. To find the pulseaudio device names one can use this command ```pacmd list-sources | awk '/name:.+\.monitor/'```
2. Then `cvlc screen:// --input-slave=pulse://`**AUDIODEVICE FROM 1**` :screen-fps=`**FPS**` :screen-caching=`**CACHING DELAY**` --sout '#transcode{vcodec=`**OUTPUT VIDEO CODEC**`,vb=0,width=`**OUTPUT WIDTH**`,height=`**OUTPUT HEIGHT**`,acodec=`**OUTPUT AUDIO CODEC**`}:http{mux=`**OUTPUT MUXER**`,dst=:`**OUTPUT PORT**`/}'`

**Comment by thermatk** [comment] 2019-05-19 10:14
Until PipeWire is ready, that's all I could find about Wayland screencasting
https://wiki.gnome.org/Projects/Mutter/RemoteDesktop, which is an implementation of interface previously mentioned here. But considering Wayland isn't ready (at least in screencasting sense), couldn't you add an X11-only codepath for now?

**Comment by ZanderBrown** [comment] 2019-05-22 13:45
https://github.com/benzea/gnome-screencast

**Comment by Rafostar** [comment] 2019-05-28 19:22
> https://github.com/benzea/gnome-screencast

That one uses Miracast. People tend to mix those two, but Chromecast and Miracast are two totally different protocols!

@thermatk I have been getting positive results with similar commands as you did, but with GStreamer. GStreamer was designed for streaming after all and it supports both x11 and Wayland through PipeWire.

> I don't know what the codec requirements for chromecast are, but should be doable

Yeah, Chromecast is not only picky about codecs but it also needs a proper full http server (not tcp) and a few HTTP Headers on a source web page.

Anyway, I was successfully able to stream desktop to Chromecast as long as network connection (between  router and Chromecast was fast and stable). Because Chromecast does NOT have an option to turn off buffering, delay is increasing when it cannot keep up with receiving data (which makes me wonder how Google plans to use Stadia gaming service on it). Still needs more tuning and testing...

**Comment by ZanderBrown** [comment] 2019-05-30 14:26
@Rafostar my point was more that it streams gnome-shell regardless of x11 vs wayland, where/how it sends the stream is superfluous

**Comment by Rafostar** [comment] 2019-05-31 14:17
Anyone up for some testing? [cast-to-tv-desktop-addon](https://github.com/Rafostar/cast-to-tv-desktop-addon)

```
cd /tmp
git clone https://github.com/Rafostar/cast-to-tv-desktop-addon.git
cd cast-to-tv-desktop-addon
make install
```

Restart gnome-shell, enable extension, go to Cast to TV settings and click `Install npm modules`.
You should see a text saying that Desktop Add-on is being installed printed in built-in terminal.

Also required is GStreamer-1.0 with it's plugins-good package.

This is early WIP, but I would appreciate it if everyone who tested it reported back here. No sound for now (audio support is ready). We will enable audio if initial tests will be successful.

**Comment by mooninite** [comment] 2019-05-31 17:09
I tried it on gnome shell 3.32.2, but it failed to load:

gnome-shell[1886]: Extension "cast-to-tv-desktop-addon@rafostar.github.com" had error: ImportError: No JS module 'shared' found in search path

**Comment by Rafostar** [comment] 2019-05-31 18:06
> I tried it on gnome shell 3.32.2, but it failed to load:
> 
> gnome-shell[1886]: Extension "[cast-to-tv-desktop-addon@rafostar.github.com](mailto:cast-to-tv-desktop-addon@rafostar.github.com)" had error: ImportError: No JS module 'shared' found in search path

You didn't remove Cast to TV v9 before installing, right? For this to work you **need to have both** extensions enabled. And what was your linux distro?

**Comment by mooninite** [comment] 2019-05-31 21:40
Sorry I was unaware of the dependency on the two extensions. I have now installed both of them from the latest git master checkouts. The cast-to-tv-desktop-addon extension now activates, but the Cast to TV extension settings window displays an error: 

    TypeError: nodePath is null
    
    Stack trace:
      @/home/michael/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/prefs.js:11:7
      _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:59:13
      _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:74:31
      _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
      main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
      @<main>:1:43

Distro: Fedora 30 x86_64

**Comment by mooninite** [comment] 2019-05-31 21:52
Sorry, I was unaware of the dependency between the two. I have now installed both extensions from the latest git master checkouts. They are now activated and appear to be functioning.

When I select "Desktop" from the cast selection my Chromecast changes to black for a second, then it looks like a movie player interface appears playing a video called "none" for a few seconds and then it flashes back to black and then displays a blue cast icon in the middle of the TV. No desktop is displayed. I've tried activating the Desktop cast a few times and the result is the same.

I can cast a video to the Chromecast with no problem.

Distro: Fedora 30 x86_64 (ffmpeg 4.1.3)

**Comment by Rafostar** [comment] 2019-06-01 05:14
@mooninite If you have it working for videos I assume that you installed nodejs and all the other dependencies as stated in [readme for fedora](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv#fedora).

As I written before, for desktop streaming also required is **GStreamer-1.0** with its **plugins-good**, **plugins-bad** and **plugins-ugly** packages (I forgot to mention some of these plugins earlier, sorry).

I know that it is a lot, but all provide required elements for desktop recording and encoding.

So in case of Fedora:
```
sudo dnf install gstreamer1 gstreamer1-plugins-base gstreamer1-plugins-good gstreamer1-plugins-bad-free gstreamer1-plugins-ugly
```

If I didn't forget anything you should be able to cast a desktop after installing above.

**Comment by mooninite** [comment] 2019-06-01 14:08
Yes, nodejs is installed. I'm using an X11 session. I also have had all of the gstreamer1 packages installed.

    gstreamer1-plugins-bad-free-1.16.0-1.fc30.x86_64
    gstreamer1-plugins-bad-freeworld-1.16.0-1.fc30.x86_64
    gstreamer1-plugins-base-1.16.0-1.fc30.i686
    gstreamer1-plugins-base-1.16.0-1.fc30.x86_64
    gstreamer1-plugins-good-1.16.0-1.fc30.x86_64
    gstreamer1-plugins-good-gtk-1.16.0-1.fc30.x86_64
    gstreamer1-plugins-ugly-1.16.0-2.fc30.x86_64
    gstreamer1-plugins-ugly-free-1.16.0-2.fc30.x86_64

**Comment by Rafostar** [comment] 2019-06-01 15:31
@mooninite Could you send me output of
```
ls ~/.local/share/gnome-shell/extensions/cast-to-tv-desktop-addon@rafostar.github.com
```
I want to make sure all files are in place.

**Comment by mooninite** [comment] 2019-06-01 16:49
<pre><font color="#00AFD7">$ </font>ls ~/.local/share/gnome-shell/extensions/cast-to-tv-desktop-addon@rafostar.github.com
extension.js  metadata.json  <font color="#0087FF">node_scripts</font>  package-lock.json  widget.js
LICENSE       <font color="#0087FF">node_modules</font>   package.json  README.md</pre>

**Comment by Rafostar** [comment] 2019-06-01 18:54
Everything seems to be installed properly. I went through the code to try to find possible cause. The first thing I noticed is that the screen resolution is set to 1920x1080. Is yours screen res different?
I will try installing this on Fedora live iso next week to see if I run into any problems.

**Comment by mooninite** [comment] 2019-06-02 00:39
Yes, I am running a 2560x1440 144hz monitor.

**Comment by Rafostar** [comment] 2019-06-02 05:47
> Yes, I am running a 2560x1440 144hz monitor.

And that is the reason, why it is not working for you. There is no resolution detection and scaling yet (I will try to implement those in the future). Can you temporarily change system resolution to 1920x1080@60 and try casting again?

**Comment by mooninite** [comment] 2019-06-05 23:52
OK. Changing to 1080p does have it working. There is about a 5 second delay though. Single CPU thread usage at about ~65%.

CPU: 4790k
GPU: NVIDIA 750Ti (430.14 driver)

**Comment by 1989gironimo** [comment] 2019-06-09 11:57
The desktop-addon cannot find my Chromecast, but Chromium can.
Tried to configure it in the settings dialogue but it's not there as well.

**Comment by Rafostar** [comment] 2019-06-09 14:38
> The desktop-addon cannot find my Chromecast, but Chromium can.
> Tried to configure it in the settings dialogue but it's not there as well.

PC and Chromecast need to be on the same network. MDNS has problems finding Chromecast on some network configurations (depends on router and network card). In that case check your current Chromecast IP in either router web config or google home app and use [cast-to-tv-config](https://github.com/Rafostar/cast-to-tv-config) to manually set IP from linux terminal.

**Comment by 1989gironimo** [comment] 2019-06-09 15:33
Ok, after manual configuration it can find the chromecast, but after enabling the desktop stream it just displays "none" as the video title and a black screen with the casting symbol.
I'm using it on a debian based distro with 1920x1080 as the display resolution.

(everything else -music etc.- doesn't work either, so it may be something else)

**Comment by Rafostar** [comment] 2019-06-09 15:51
@1989gironimo Don't know what your network configuration is, but this might be a firewall issue. When you open extension settings you should see your PC local IP at the bottom. Try changing your receiver type to web browser and accessing that link using web browser on other device (other pc or smartphone) on the same network that Chromecast is.

**Comment by 1989gironimo** [comment] 2019-06-09 16:02
Ok, streaming works now, I had to edit iptables with `sudo iptables -I INPUT -p tcp --dport 4000 -j ACCEPT
`
I suggest to add this to the documentation.
But desktop streaming still doesn't work, it just hangs as described before, where can I start debugging? :)

**Comment by Rafostar** [comment] 2019-06-09 16:28
> Ok, streaming works now, I had to edit iptables with `sudo iptables -I INPUT -p tcp --dport 4000 -j ACCEPT `
> I suggest to add this to the documentation.

OK. I will add this to docs. Interesting that Debian default firewall is that aggressive, as I usually test this on Ubuntu and Fedora and both allow accessing local computers without firewall tinkering. Since that got you working it might be possible that MDNS device scanning can be fixed the same way. It uses UDP port 5353 btw. More info on [wikipedia](https://en.wikipedia.org/wiki/Multicast_DNS).

> But desktop streaming still doesn't work, it just hangs as described before, where can I start debugging? :)

Desktop streaming is a work in progress and I have not implemented debugging in that part yet. Sorry. For now just make sure you have gstreamer1.0 with all its plugins (do not mistake gstreamer 0.10 with 1.0 as they are different). And it looks like Debian have some of the required GStreamer binaries in separate package called `gstreamer1.0-tools` make sure you have that installed too.

**Comment by 1989gironimo** [comment] 2019-06-09 16:58
It's PureOS, not debian itself. But adding that to the docs is still usefull nonetheless.
Adding 5353 to iptables doesn't do anything, maybe there's something missing as well, I'll have a look the next few days.

**Comment by Rafostar** [comment] 2019-06-09 17:07
OK. Remember that on debian based distros besides `gstreamer1.0` and its plugins also need `gstreamer1.0-tools` so check if their versions match too.

**Comment by 1989gironimo** [comment] 2019-06-09 20:11
I've verified, which gstreamer1.0 package may be missing and what the error means, but it seems, there are two different packages which can be installed for the same base functionality:
- gstreamer1.0-python3-dbg-plugin-loader
- gstreamer1.0-python3-plugin-loader

Everything else (incl. the plugins good, bad, ugly) is installed and in my opinion it doesn't make a real difference which of both are installed.

**Comment by thermatk** [comment] 2019-06-14 19:49
Tested, works great on Manjaro (Arch) X11. CPU load is barely to notice on desktop Kaby Lake

**Comment by Rafostar** [comment] 2019-06-14 20:30
@thermatk Thanks for testing. Using the command you provided earlier
`pacmd list-sources | awk '/name:.+\.monitor/'`
list of system audio output devices can be obtained. After determining your currently used sound device name, run below commands while **replacing only source in second line** with your own device name:

```
pacmd load-module module-null-sink sink_name=cast_to_tv sink_properties=device.description=WirelessDisplay
pacmd load-module module-loopback source=alsa_output.pci-0000_00_01.1.hdmi-stereo.monitor sink=cast_to_tv adjust_time=5 latency_msec=1 sink_dont_move=true
```

Next select new *WirelessDisplay* sink in System Settings -> Sound. On the next cast, this should enable audio on the receiver while not playing it on PC (hearing it from both devices with delay is annoying).

Everyone interested in having audio, please try it and let me know if it works correctly. All changes using pacmd are temporary until next pulseaudio/system restart, so there is no risk in breaking os configuration.

**Comment by thermatk** [comment] 2019-06-16 11:01
@Rafostar 
tested, sound is working, it's in sync with picture as far as I can tell after a small test. There is a nasty bug I found in the video part though, which I didn't see before: it's leaking memory, if you stop streaming.
So I start streaming desktop, RAM consumption is stable, then if I unplug the Chromecast or stream on it from another device, the desktop RAM consumption is linearly growing until it eats all 16 GB and X.org dies. The only way to prevent death I found is to kill the `gst-launch-1.0` process

**Comment by thermatk** [comment] 2019-06-16 11:05
Narrowed down, the process which actually goes berserk and starts eating RAM is Xorg. Maybe one should somehow detect that it's not streaming and tell it not to cache, I have no idea where it's coming from.

**Comment by Rafostar** [comment] 2019-06-16 20:43
@thermatk `gst-launch-1.0` should be automatically killed when streaming stops. According to your description it doesn't when you start streaming from another device while desktop streaming was active. Did I understood correctly? Does `gst-launch-1.0` process disappears when streaming is stopped using stop button from gnome top bar remote?

**Comment by thisbesonic** [comment] 2019-07-07 16:52
will the "cast-to-tv Desktop" also work via webbrowser? 

My LG TV's miracast screen share does not work at all with miraclecast, so I thought this could be a solution via the tv inbuilt browser.

**Comment by Rafostar** [comment] 2019-07-07 17:45
> will the "cast-to-tv Desktop" also work via webbrowser?
> 
> My LG TV's miracast screen share does not work at all with miraclecast, so I thought this could be a solution via the tv inbuilt browser.

If your browser supports HTML5 and works with Cast to TV normally, which user Plyr web player, then it should work too. You can always test web support using demo video on [Plyr website](https://plyr.io/). Also browser should support video autostart, otherwise you must click play button quickly after page loads (cached data gets removed from memory and stream cannot start with missing headers).

Please note all the current bugs mentioned above and that lately I have been working on streaming core functionality which uses my other [gst-rec](https://github.com/Rafostar/gst-rec) terminal app (it creates web streams but doesn't come with web player). It is more mature as I hadn't time to move all improvements from it to desktop stream extension yet. Please check it out and see examples on its page (http server example might be useful to you).

**Comment by deisi** [comment] 2019-08-30 19:38
So I had [gnome-shell-extension-cast-to-tv](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv) working. Then I installed [cast-to-tv-desktop-addon](https://github.com/Rafostar/cast-to-tv-desktop-addon). Now Its not working any more and I see 
```
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: Restarting Cast to TV server
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: Started Cast to TV service
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: internal/modules/cjs/loader.js:775
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     throw err;
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     ^
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: Error: Cannot find module 'gstreamer-recorder'
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: Require stack:
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: - /home/malte/.local/share/gnome-shell/extensions/cast-to-tv-desktop-addon@rafostar.github.com/node_scripts/addon.js
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: - /home/malte/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts/addons-importer.js
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: - /home/malte/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts/bridge.js
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: - /home/malte/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts/server.js
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Function.Module._load (internal/modules/cjs/loader.js:677:27)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Module.require (internal/modules/cjs/loader.js:830:19)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at require (internal/modules/cjs/helpers.js:68:18)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Object.<anonymous> (/home/malte/.local/share/gnome-shell/extensions/cast-to-tv-desktop-addon@rafostar.github.com/node_scripts/addon.js:2:19)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Module._compile (internal/modules/cjs/loader.js:936:30)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Module.load (internal/modules/cjs/loader.js:790:32)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Function.Module._load (internal/modules/cjs/loader.js:703:12)
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     at Module.require (internal/modules/cjs/loader.js:830:19) {
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:   code: 'MODULE_NOT_FOUND',
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:   requireStack: [
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     '/home/malte/.local/share/gnome-shell/extensions/cast-to-tv-desktop-addon@rafostar.github.com/node_scripts/addon.js',
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     '/home/malte/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts/addons-importer.js',
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     '/home/malte/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts/bridge.js',
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:     '/home/malte/.local/share/gnome-shell/extensions/cast-to-tv@rafostar.github.com/node_scripts/server.js'
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]:   ]
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: }
Aug 30 21:27:40 mtop org.gnome.Shell.desktop[1669]: Restarting Cast to TV server

```
all over my `journalctl`. If I see it correctly [gstreamer-recorder](https://github.com/Rafostar/gstreamer-recorder) is missing.

I'm on Arch Linux Gnome 3.32.2. Installed all addons from github current master branch.
I have installed all gstream stuff I think. I'm using wayland.

**Comment by Rafostar** [comment] 2019-08-30 20:19
@deisi Glad to hear it works now (and even on Wayland). `install npm modules` step after enabling addons is necessary as it installs additional npm modules that this addon requires (I do not want to force users to install them if they wont be installing addons).

> Sidequestion, how do you control the cast once you started it.

There should appear a widget to control the playback on gnome top bar. What source did you use to install gnome-extension (extensions page, git or arch package) and what version are you using (in settings about page)?

**Comment by deisi** [comment] 2019-08-30 20:58
> do you have gsettings installed

gsettings is installed.

> install npm modules step after enabling addons is necessary as it installs additional npm modules that this addon requires

Is there any use case  for this addon if the modules are not installed?

> What source did you use to install gnome-extension
I think for https://extensions.gnome.org/extension/1544/cast-to-tv/ I used the extension webpage and forcast-to-tv-desktop-addon  I used the github repo.

**Comment by Rafostar** [comment] 2019-08-30 21:14
@deisi Glad it works. Can you also check casting desktop with sound? I posted instructions few posts above in this thread. And if you manage to find any other non-desktop streaming related problems, please open a separate github issue.

**Comment by deisi** [comment] 2019-08-30 21:17
Okay, for today I'm too tired to try It now. I have put it on my list for tomorrow.

**Comment by deisi** [comment] 2019-08-31 09:54
And now desktop cast is not working any more. I see this in my journalctl. Looks like a pipewire problem to me. Chromecast showing some connection things but then there is never any video. (rebot and reinstall of npm modules made no difference)

Video (with audio) cast is working. However I found out that the chromecast cant play VP9 videos. Is that correct? Isn't VP9 the thing google is trying to push to everybody and now they don't have it in their own stick?

Also I keep having trouble with the remote control. When ever the playback fails, the remote control vanishes. However the chromecast doesn't go back to its default desktop, but rather stays in some kind of pseudo playing state. Due to that I find my self using the https://extensions.gnome.org/extension/1955/cast-control/ addon all the time, because this doesn't go away.

```
Aug 31 11:47:52 mtop pipewire[4002]: [E][module-protocol-native.c:336 client_new()] no peersec: Protocol not available
Aug 31 11:47:52 mtop pipewire[4002]: [E][module-autolink.c:247 try_link_port()] module 0x55d5d21d4c40: can't link node 'No matching Node found'
Aug 31 11:47:55 mtop gnome-shell[1530]: Cast Control 2: GET Request Started to Cast API at http://localhost:3000/device
Aug 31 11:47:55 mtop gnome-shell[1530]: Cast Control 2: Now refreshed with API... waiting until next 15000ms
Aug 31 11:47:56 mtop pipewire[4002]: [E][module-protocol-native.c:336 client_new()] no peersec: Protocol not available
Aug 31 11:47:56 mtop pipewire[4002]: [E][module-autolink.c:247 try_link_port()] module 0x55d5d21d4c40: can't link node 'No matching Node found'
Aug 31 11:47:59 mtop pipewire[4002]: [E][module-protocol-native.c:336 client_new()] no peersec: Protocol not available
Aug 31 11:47:59 mtop pipewire[4002]: [E][module-autolink.c:247 try_link_port()] module 0x55d5d21d4c40: can't link node 'No matching Node found'
Aug 31 11:48:02 mtop pipewire[4002]: [E][module-protocol-native.c:336 client_new()] no peersec: Protocol not available
Aug 31 11:48:02 mtop pipewire[4002]: [E][module-autolink.c:247 try_link_port()] module 0x55d5d21d4c40: can't link node 'No matching Node found'
```

**Comment by Rafostar** [comment] 2019-08-31 11:48
@deisi Thanks for testing.

> However I found out that the chromecast cant play VP9 videos. Is that correct?

Yes. Chromecast does not support VP9 nor h265. Only Chromecast Ultra supports them. See supported media [here](https://developers.google.com/cast/docs/media).

> However the chromecast doesn't go back to its default desktop, but rather stays in some kind of pseudo playing state.

When Chromecast crashes it stays on black BG with cast logo. This is normal, ignore it. Just cast something other to get it to work again or wait a while and it will give up and go back to showing you colourful pictures.

Regarding errors. Only Wayland uses **pipewire** for desktop, **X11** should work better, thats why I written on desktop-addon github page to use only X11 for now.

> My laptop just wen into standby while casting.

I am not disabling standby in this extension (and I am not going to). If you have standby enabled either disable it or install some other extension like [Caffeine](https://extensions.gnome.org/extension/517/caffeine/) to toggle it on/off.

> the video became green and was flickering even on my local screen. The same was shown on the TV.

We are just recording screen and streaming it to TV. If it was green on your PC, then it is a problem with your video player.

> The delay becomes bigger and bigger.

I need to add an option to reduce bitrate while streaming desktop, otherwise it grows due to video caching, that Google does not allow me to disable.

**Comment by Rafostar** [comment] 2019-08-31 11:54
This thread is too long. We now have desktop streaming on a very preliminary stage. I know that it somehow works. Audio works too, but auto-enable needs to be integrated into extension.

I am closing this and strongly encourage to wait with desktop casting before I figure out how to resolve all the bugs that we were able to find in this thread.

**Closed by Rafostar** 2019-08-31 11:54 UTC

**Comment by Rafostar** [comment] 2020-04-19 07:33
If anyone is still interested in desktop streaming, then the relevant add-on for GNOME 3.34+ is now available on GNOME Extensions website:
[https://extensions.gnome.org/extension/2977/cast-to-tv-desktop-stream-add-on](https://extensions.gnome.org/extension/2977/cast-to-tv-desktop-stream-add-on)

**Comment by DavidDevoogdt** [comment] 2020-12-21 09:52
can you make it work for GNOME 3.38?
